### ISSUE TITLE
time to use this empty repository?

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zf3#1]
Hello, is there a time to use this repository? or we can just rename zendframework/zf2 to zendframework/zf ?

**Comment by Xerkus** [comment]
I don't think it can ever be renamed or deleted. Same way as zf1 svn repo is still there.

**Comment by stevleibelt** [comment]
Why not start in a fresh root namespace meaning a new github organisation like "zendframework3"?
This would have the following benefits:
* zf2 stuff stays where it is
* no links will be broken
* the number of repositories in "zendframework" always reflects the available modules from the zendframework 2 (same for the upcomming zendframework3)

**Comment by Maks3w** [comment]
Too early for to discuss nothing about this.

**Comment by samsonasik** [comment]
:( , I think it's not too early to discuss this to get plan for zf3 this year on the road smoothly

Warm regards,

Abdul Malik Ikhsan

Pada 26 Jul 2015, pukul 01.36, Maks3w <notifications@github.com> menulis:

**Comment by weierophinney** [comment]
> Why not start in a fresh root namespace meaning a new github organisation like "zendframework3"?

No.

ZF3 will essentially be ZF2, adopting those components we have elected to bump to v3. There is no reason to move to a new organization, and, in fact, that would be more confusing, considering the components stay under the zendframework organization.

Additionally, I'd like to point out that the official package name is `zendframework/zendframework`. No version is present in the name. (This is not true of the ZF1 package; see notes at the bottom of this comment.)

We can continue doing ZF development in the zf2 repository, which provides a clean upgrade path for users going from ZF2 to ZF3.

The main point of contention at this point is that the repository is named "zf2". Fortunately, at this time, GitHub has [recently announced redirects for repositories](https://github.com/blog/1508-repository-redirects-are-here), which occur automatically whenever you *rename* a repository. As such, we can easily rename the "zf2" repository to "zendframework" or "zf". I will put in a question to my contacts at GitHub to see if these are persistent indefinitely; if so, we should have no problems. Users can update when they want, but the links they have currently should continue to exist.

@Maks3w notes:

> Too early for to discuss nothing about this.

I'd appreciate if you'd ask before making comments like this. We have a plan, and we've been executing on it; right now, the open items are:

- Service Manager refactor (we're finalizing discussions currently; likely completion in the next few weeks)
- Event Manager refactor (in progress, with likely completion in the next few weeks)
- Potential refactors of validators (which would have ramifications on input filter and forms)
- PSR-7 support for the MVC (not yet started)
- Middleware-based microframework (in progress)

We've also already accomplished a fair bit:

- Separation of components into their own repositories.
- PSR-7 implementation.
- Middleware foundation.

ZF3 is definitely happening this year, and we should have testable versions available in the next 4-8 weeks.

## About ZF1

ZF1 has its own repository for a number of reasons:

- That repository requires a Contributor License Agreement be in place in order for us to accept contributions. Starting with ZF2, we no longer require the CLA. Different processes require different repositories.
- We didn't move ZF1 development to GitHub until a year or two after ZF2 was released. As such, the ZF2 repo history diverges significantly from ZF1, while still sharing some common history. Merging the two would be significantly difficult, and inflate the repository size.
- Speaking of repo size, the ZF1 repository includes the documentation, which in essence triples or more the size of a checkout. This would be a serious hurdle for users in bandwidth-restricted areas who only want to work on ZF2.
- ZF1 development is still active, which would require a dedicated branch on the repository. Having a separate repository instead makes sense. (You could argue this for the 2.4 LTS release as well, except that our process around it is quite different than ZF1.)
- Because the repositories were originally separate, we had to use different package names, as packagist does not allow using the same package name across multiple repositories. Merging them at this point would require updating every single ZF1 installation that uses Composer.

Essentially, having the ZF1 repository separate is due to historical choices we made, but those do not have bearing on the relationship of ZF2 to ZF3.

**Comment by stevleibelt** [comment]
@weierophinney 
thanks for your time to create such a detailed answere. I really appreciate that fact since it gives a really good feeling that you listen to what the community thinks and says.
Really, big respect form my side :-).

**Comment by gianarb** [comment]
@weierophinney Thanks for this comment!
A public todo list with your work is very important to share with all community these operations.

@Maks3w the [deadline](http://framework.zend.com/blog/announcing-the-zend-framework-3-roadmap.html) of ZF3 is public.. 

> We have already done a lot of thinking (and coding!) in this direction, and we intend to release ZF3 in Q3 2015 — yes, this year!

Why "Too early for to discuss nothing about this."? The Q3 2015 is near!!! :)  :+1:
